### ISSUE TITLE
Is there a way to get an existing <md> element to render new markdown that wasn't initially there?

### ISSUE THREAD

**Issue by dallaylaen** [MarketingPipeline/Markdown-Tag#3]
### Suggestion / Feature Request

If there is, it should be in the doc; if not, here's a feature request.

Thank you!

**Comment by MarketingPip** [comment]
As of right now Markdown Tag does not have this option - this will be added in **ASAP.** 


Currently marking this issue as a bug for right now. Will take this on myself when possible or assign this to anyone willing to take this on.

**Comment by MarketingPip** [comment]
Closing this & moving this to a bug report for this issue. [[Bug]: Tag(s) added after page load do not render · Issue #5 ](https://github.com/MarketingPipeline/Markdown-Tag/issues/5)

**Comment by MarketingPip** [comment]
@dallaylaen - re-opening this issue just to inform you this request has been completed. If any suggestions further to the usage or the documentation etc. Feel free to add your input again! And thank you for your suggestion / note of this! :+1: 

## How to <b>render</b> new text or a new Markdown Tag added to HTML:

Call this function using a onclick etc..

```
renderMarkdown();
```

Hope this helps with whatever you were building / or plan to create! :smile: 
Apologizes for the delay on this as well!
