### ISSUE TITLE
Whitelist / Blacklist Markdown features

### ISSUE THREAD

**Issue by solidevolution** [MarketingPipeline/Markdown-Tag#4]
### Suggestion / Feature Request

We often have the use case, that we got styled content (html or markdown) from external systems.
Mostly the features are restricted by the cms editor but we have to ensure that we restrict markdown features for the content editor.

As example, we only want **bold** formatting and links but not the possibility to use paragraphs, breaks, headlines or images.

**Comment by MarketingPip** [comment]
This is NOT the purpose of this project. The purpose of this project is to style the content in **100% true flavor** of the syntax style chosen. 

Tho - to achieve this your best option would just be modifying this script by changing the markdown parser options to your own personal needs. For any further questions on that - seek documentation / help from the Markdown Parser you use. 

Marking this as closed.
