### ISSUE TITLE
[Feature Request / Suggestion]: Support code syntax highlighting for GFM

### ISSUE THREAD

**Issue by jcubic** [MarketingPipeline/Markdown-Tag#6]
### Suggestion / Feature Request

It would be nice to have support for syntax highlighting:

````

```javascript
function foo() {
}
```

````

as

```javascript
function foo() {
}
```

You can use [PrismJS](https://github.com/PrismJS/prism) for that. You can use it as an external dependency that need to included on the page.

**Comment by MarketingPip** [comment]
This is actually on the to-do list! If you are willing you are willing to take a jab at adding current support. But waiting to see if another user is willing to commit their fork. As I do believe it has this feature already! :) 

Thank you for your input tho @jcubic 

ps; happy friday!

**Comment by MarketingPip** [comment]
@jcubic - this request has been fulfilled. Keep posted to the repo to see the reflected changes on all version! 

Sorry for any delays & hoping you had a great weekend :+1:

> ps; don't forget to share Markdown Tag with your friends & family etc. :smile:

**Comment by jcubic** [comment]
Awesome. Thanks.
